# 1. Database URL (Points to your local MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/talentlink_db?createDatabaseIfNotExist=true

# 2. Your MySQL Credentials (Update these!)
spring.datasource.username=root
spring.datasource.password=cyberhunter

# 3. Hibernate logic (Automatically creates/updates tables)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 4. Turn off H2 to avoid confusion
spring.h2.console.enabled=false